# Generated by Django 4.1.7 on 2023-05-30 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
